In [1]:
import numpy as np

In [3]:
A = np.round(10*np.random.rand(5,4))

In [5]:
A

array([[ 8.,  2.,  7.,  2.],
       [10.,  8.,  3.,  9.],
       [ 5.,  0.,  3.,  3.],
       [10.,  1.,  4., 10.],
       [ 8.,  8.,  5.,  0.]])

In [7]:
A[1,2]

3.0

In [9]:
A[1,:]

array([10.,  8.,  3.,  9.])

In [13]:
A[ :,1]

array([2., 8., 0., 1., 8.])

In [15]:
A[1:3,2:4]

array([[3., 9.],
       [3., 3.]])

In [17]:
A

array([[ 8.,  2.,  7.,  2.],
       [10.,  8.,  3.,  9.],
       [ 5.,  0.,  3.,  3.],
       [10.,  1.,  4., 10.],
       [ 8.,  8.,  5.,  0.]])

In [19]:
A.T

array([[ 8., 10.,  5., 10.,  8.],
       [ 2.,  8.,  0.,  1.,  8.],
       [ 7.,  3.,  3.,  4.,  5.],
       [ 2.,  9.,  3., 10.,  0.]])

In [21]:
import numpy.linalg as la

In [25]:
la.inv(np.random.rand(3,3))

array([[-1.06034941,  1.92808167, -2.79964434],
       [ 2.34147081, -1.50457123, -0.03650026],
       [-0.99150743,  0.61263419,  2.60929274]])

In [27]:
A.sort(axis=0)

In [29]:
A

array([[ 5.,  0.,  3.,  0.],
       [ 8.,  1.,  3.,  2.],
       [ 8.,  2.,  4.,  3.],
       [10.,  8.,  5.,  9.],
       [10.,  8.,  7., 10.]])

In [31]:
A.sort(axis=1)

In [33]:
A

array([[ 0.,  0.,  3.,  5.],
       [ 1.,  2.,  3.,  8.],
       [ 2.,  3.,  4.,  8.],
       [ 5.,  8.,  9., 10.],
       [ 7.,  8., 10., 10.]])

In [35]:
A = np.arange(100)

In [37]:
B = A[[3,5,6]]

In [39]:
B

array([3, 5, 6])

In [41]:
B[0]=150

In [43]:
B

array([150,   5,   6])

In [45]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
B = A[A<40]

In [49]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [51]:
B = A[(A<40)&(A>30)]

In [53]:
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [55]:
A = np.arange(np.random.rand(2,2))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
A = np.random.rand(2,2)

In [59]:
A

array([[0.01075471, 0.1666159 ],
       [0.34952067, 0.97411431]])

In [61]:
A = A+5

In [63]:
A

array([[5.01075471, 5.1666159 ],
       [5.34952067, 5.97411431]])

In [69]:
A = np.round(10*np.random.rand(2,3))

In [73]:
A

array([[ 0.,  4., 10.],
       [ 1.,  3., 10.]])

In [75]:
B = np.round(10*np.random.rand(2,2))

In [77]:
B

array([[10.,  5.],
       [ 2.,  5.]])

In [79]:
C = np.hstack((A,B))

In [81]:
C

array([[ 0.,  4., 10., 10.,  5.],
       [ 1.,  3., 10.,  2.,  5.]])

In [83]:
A = np.random.permutation(np.arange(10))

In [85]:
A

array([5, 7, 1, 3, 8, 4, 9, 2, 6, 0])

In [87]:
A.sort()

In [89]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [93]:
B = np.random.rand(1000000)
%timeit sum(B)
%timeit np.sum(B)


98.3 ms ± 10.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
869 µs ± 90.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [95]:
def mySum(G):
    s=0
    for x in G:
        s+=x
        return s

In [99]:
%timeit mySum(B)

256 ns ± 2.96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
